### ISSUE TITLE
DVSA CREATE_failed

### ISSUE THREAD

**Issue by mathangi28** [OWASP/DVSA#34]
I am trying to deploy DVSA from serverless repository, every time it throws create failed error, can anyone help me through this?

**Comment by 4ppsec** [comment]
I believe this is due to leftovers from previous deployments. This will be fixed in the new version that will be release within a few weeks.

please try to manually delete:
1. Lambda function named: `DVSA-INIT`
2. Any CloudWatchLog starts with `/aws/lambda/DVSA-`
3. S3 buckets starting with `dvsa`

If that doesn't help, please post a screenshot of the deployment failure from the cloudformation console

**Comment by mathangi28** [comment]
Thank you sir, I installed it locally , it’s running fine
